import { Bellefair, Barlow, Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const bellefair = Bellefair({
  variable: "--font-bellefair",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${bellefair.variable} ${barlowCondensed.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
